# Generated by Django 4.2.4 on 2023-09-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usosLearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='BirthDay',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Country',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='JobType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='LastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
