# Generated by Django 4.2.5 on 2023-09-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usosLearning', '0002_alter_user_birthday_alter_user_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='EmailAddress',
            new_name='email',
        ),
    ]
