# Generated by Django 4.2.5 on 2023-09-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usosLearning', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
