# Generated by Django 4.2.5 on 2023-09-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usosLearning', '0007_alter_user_phonenumber_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
