# Generated by Django 4.2.5 on 2023-09-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usosLearning', '0008_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
