# Generated by Django 4.2.5 on 2023-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usosLearning', '0014_rename_subject_course_subjectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imageURL',
            field=models.TextField(),
        ),
    ]
